import React, { useState, useEffect } from 'react'
import { useLocation, useNavigate, Link } from 'react-router-dom'
import { 
  MapPin, Calendar, Clock, DollarSign, Users, AlertTriangle,
  ChevronDown, ChevronUp, Download, Share2, ArrowLeft,
  Sun, Cloud, Mountain, Fuel, Wifi, Package, Phone,
  Utensils, Camera, CheckCircle, Check, Copy
} from 'lucide-react'
import './ItineraryView.css'

function ItineraryView() {
  const location = useLocation()
  const navigate = useNavigate()
  const [tripPlan, setTripPlan] = useState(null)
  const [expandedDays, setExpandedDays] = useState({})
  const [activeTab, setActiveTab] = useState('itinerary')
  const [downloadStatus, setDownloadStatus] = useState(null) // 'downloading', 'success', 'error'
  const [shareStatus, setShareStatus] = useState(null) // 'copied', null

  useEffect(() => {
    if (location.state?.tripPlan) {
      setTripPlan(location.state.tripPlan)
      // Expand first day by default
      setExpandedDays({ 1: true })
    }
  }, [location.state])

  if (!tripPlan) {
    return (
      <div className="itinerary-empty">
        <h2>No Trip Plan Found</h2>
        <p>Please create a trip plan first.</p>
        <Link to="/trip-wizard" className="create-btn">
          Create Trip Plan
        </Link>
      </div>
    )
  }

  const toggleDay = (dayNum) => {
    setExpandedDays(prev => ({
      ...prev,
      [dayNum]: !prev[dayNum]
    }))
  }

  const expandAllDays = () => {
    const all = {}
    tripPlan.daily_plan?.forEach(day => {
      all[day.day] = true
    })
    setExpandedDays(all)
  }

  const collapseAllDays = () => {
    setExpandedDays({})
  }

  const formatCurrency = (amount) => {
    return `PKR ${amount?.toLocaleString() || 0}`
  }

  const getBudgetStatusColor = (status) => {
    switch (status) {
      case 'under_budget': return '#4caf50'
      case 'on_budget': return '#ff9800'
      case 'over_budget': return '#f44336'
      default: return '#888'
    }
  }

  // Generate text content for download/share
  const generateTripPlanText = () => {
    if (!tripPlan) return ''
    
    let text = `
========================================
${tripPlan.trip_title || `Trip to ${tripPlan.destination}`}
========================================

TRIP DETAILS
------------
• Destination: ${tripPlan.destination}
• Duration: ${tripPlan.duration_days} days
• Travelers: ${tripPlan.num_people} (${tripPlan.travel_type})
• Budget: PKR ${tripPlan.budget_pkr?.toLocaleString()}
• Style: ${tripPlan.travel_style}
• Best Time: ${tripPlan.best_time_to_visit || 'Varies'}

DAILY ITINERARY
---------------
`
    tripPlan.daily_plan?.forEach(day => {
      text += `
Day ${day.day}: ${day.title}
${day.route ? `Route: ${day.route}` : ''}
${day.transport ? `Transport: ${day.transport} (PKR ${day.transport_cost?.toLocaleString()})` : ''}
${day.hotel ? `Stay: ${day.hotel} (PKR ${day.hotel_cost?.toLocaleString()})` : ''}
`
      if (day.activities?.length > 0) {
        text += 'Activities:\n'
        day.activities.forEach(act => {
          text += `  • ${act.time}: ${act.activity} at ${act.location}\n`
        })
      }
      if (day.tips?.length > 0) {
        text += 'Tips: ' + day.tips.join(', ') + '\n'
      }
    })

    text += `
COST BREAKDOWN
--------------
• Transport: PKR ${tripPlan.cost_breakdown?.transport?.toLocaleString()}
• Accommodation: PKR ${tripPlan.cost_breakdown?.accommodation?.toLocaleString()}
• Food: PKR ${tripPlan.cost_breakdown?.food?.toLocaleString()}
• Activities: PKR ${tripPlan.cost_breakdown?.activities?.toLocaleString()}
• Miscellaneous: PKR ${tripPlan.cost_breakdown?.miscellaneous?.toLocaleString()}
• Buffer (10%): PKR ${tripPlan.cost_breakdown?.buffer?.toLocaleString()}
----------------------------------------
TOTAL: PKR ${tripPlan.cost_breakdown?.total?.toLocaleString()}
Per Person: PKR ${tripPlan.cost_breakdown?.per_person?.toLocaleString()}
`

    if (tripPlan.safety_notes?.length > 0) {
      text += `
SAFETY NOTES
------------
${tripPlan.safety_notes.map(note => `• ${note}`).join('\n')}
`
    }

    if (tripPlan.packing_checklist?.length > 0) {
      text += `
PACKING CHECKLIST
-----------------
${tripPlan.packing_checklist.filter(i => i.essential).map(item => `☐ ${item.item} ${item.notes ? `(${item.notes})` : ''}`).join('\n')}
`
    }

    if (tripPlan.emergency_contacts?.length > 0) {
      text += `
EMERGENCY CONTACTS
------------------
${tripPlan.emergency_contacts.map(c => `• ${c.name}: ${c.phone}`).join('\n')}
`
    }

    text += `
========================================
Generated by AI Pakistan Travel Guide
${new Date().toLocaleDateString()}
========================================
`
    return text
  }

  // Download trip plan as text file
  const handleDownload = () => {
    try {
      setDownloadStatus('downloading')
      
      const content = generateTripPlanText()
      const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      
      const link = document.createElement('a')
      link.href = url
      link.download = `trip-to-${tripPlan.destination?.toLowerCase().replace(/\s+/g, '-') || 'trip'}-${tripPlan.duration_days}days.txt`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
      
      setDownloadStatus('success')
      setTimeout(() => setDownloadStatus(null), 3000)
    } catch (error) {
      console.error('Download failed:', error)
      setDownloadStatus('error')
      setTimeout(() => setDownloadStatus(null), 3000)
    }
  }

  // Share trip plan
  const handleShare = async () => {
    const shareText = `Check out my trip plan to ${tripPlan.destination}! ${tripPlan.duration_days} days, ${tripPlan.num_people} travelers, PKR ${tripPlan.budget_pkr?.toLocaleString()} budget.`
    
    // Try native share API first (mobile)
    if (navigator.share) {
      try {
        await navigator.share({
          title: tripPlan.trip_title || `Trip to ${tripPlan.destination}`,
          text: shareText,
          url: window.location.href,
        })
        return
      } catch (err) {
        if (err.name !== 'AbortError') {
          console.error('Share failed:', err)
        }
      }
    }
    
    // Fallback: Copy summary to clipboard
    try {
      const summary = `
🗺️ ${tripPlan.trip_title || `Trip to ${tripPlan.destination}`}

📍 Destination: ${tripPlan.destination}
📅 Duration: ${tripPlan.duration_days} days
👥 Travelers: ${tripPlan.num_people} (${tripPlan.travel_type})
💰 Budget: PKR ${tripPlan.budget_pkr?.toLocaleString()}
💵 Total Cost: PKR ${tripPlan.cost_breakdown?.total?.toLocaleString()}

🏆 Highlights:
${tripPlan.must_visit_spots?.slice(0, 3).map(s => `• ${s}`).join('\n') || '• Check the full itinerary'}

Generated by AI Pakistan Travel Guide
      `.trim()
      
      await navigator.clipboard.writeText(summary)
      setShareStatus('copied')
      setTimeout(() => setShareStatus(null), 3000)
    } catch (err) {
      console.error('Copy failed:', err)
      alert('Could not copy to clipboard. Please try again.')
    }
  }

  return (
    <div className="itinerary-view">
      {/* Header */}
      <div className="itinerary-header">
        <button className="back-btn" onClick={() => navigate('/trip-wizard')}>
          <ArrowLeft size={18} /> Back to Wizard
        </button>
        <div className="header-content">
          <h1>{tripPlan.trip_title || `Trip to ${tripPlan.destination}`}</h1>
          <div className="trip-meta">
            <span><MapPin size={16} /> {tripPlan.destination}</span>
            <span><Calendar size={16} /> {tripPlan.duration_days} days</span>
            <span><Users size={16} /> {tripPlan.num_people} {tripPlan.travel_type}</span>
            <span><DollarSign size={16} /> {formatCurrency(tripPlan.budget_pkr)}</span>
          </div>
        </div>
        <div className="header-actions">
          <button 
            className={`action-btn ${downloadStatus === 'success' ? 'success' : ''} ${downloadStatus === 'error' ? 'error' : ''}`}
            onClick={handleDownload}
            disabled={downloadStatus === 'downloading'}
          >
            {downloadStatus === 'downloading' ? (
              <>⏳ Downloading...</>
            ) : downloadStatus === 'success' ? (
              <><Check size={16} /> Downloaded!</>
            ) : downloadStatus === 'error' ? (
              <>❌ Failed</>
            ) : (
              <><Download size={16} /> Download</>
            )}
          </button>
          <button 
            className={`action-btn ${shareStatus === 'copied' ? 'success' : ''}`}
            onClick={handleShare}
          >
            {shareStatus === 'copied' ? (
              <><Check size={16} /> Copied!</>
            ) : (
              <><Share2 size={16} /> Share</>
            )}
          </button>
        </div>
      </div>

      {/* Quick Info Cards */}
      <div className="quick-info-cards">
        <div className="info-card weather">
          <Sun size={24} />
          <div>
            <h4>Weather</h4>
            <p>{tripPlan.weather_summary || 'Check local conditions'}</p>
          </div>
        </div>
        <div className="info-card season">
          <Cloud size={24} />
          <div>
            <h4>Best Time</h4>
            <p>{tripPlan.best_time_to_visit || 'Varies by season'}</p>
          </div>
        </div>
        <div className="info-card budget" style={{ borderColor: getBudgetStatusColor(tripPlan.budget_status) }}>
          <DollarSign size={24} />
          <div>
            <h4>Budget Status</h4>
            <p style={{ color: getBudgetStatusColor(tripPlan.budget_status) }}>
              {tripPlan.budget_status?.replace('_', ' ').toUpperCase() || 'Unknown'}
            </p>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="itinerary-tabs">
        <button 
          className={`tab ${activeTab === 'itinerary' ? 'active' : ''}`}
          onClick={() => setActiveTab('itinerary')}
        >
          <Calendar size={16} /> Daily Itinerary
        </button>
        <button 
          className={`tab ${activeTab === 'costs' ? 'active' : ''}`}
          onClick={() => setActiveTab('costs')}
        >
          <DollarSign size={16} /> Cost Breakdown
        </button>
        <button 
          className={`tab ${activeTab === 'safety' ? 'active' : ''}`}
          onClick={() => setActiveTab('safety')}
        >
          <AlertTriangle size={16} /> Safety & Tips
        </button>
        <button 
          className={`tab ${activeTab === 'packing' ? 'active' : ''}`}
          onClick={() => setActiveTab('packing')}
        >
          <Package size={16} /> Packing List
        </button>
      </div>

      {/* Tab Content */}
      <div className="tab-content">
        {/* Itinerary Tab */}
        {activeTab === 'itinerary' && (
          <div className="itinerary-content animate-fade-in">
            <div className="expand-controls">
              <button onClick={expandAllDays}>Expand All</button>
              <button onClick={collapseAllDays}>Collapse All</button>
            </div>

            <div className="days-timeline">
              {tripPlan.daily_plan?.map((day, idx) => (
                <div key={day.day} className="day-card">
                  <div 
                    className={`day-header ${expandedDays[day.day] ? 'expanded' : ''}`}
                    onClick={() => toggleDay(day.day)}
                  >
                    <div className="day-number">Day {day.day}</div>
                    <div className="day-title">
                      <h3>{day.title}</h3>
                      {day.route && <span className="day-route"><MapPin size={14} /> {day.route}</span>}
                    </div>
                    <div className="day-cost">
                      {formatCurrency((day.transport_cost || 0) + (day.hotel_cost || 0) + (day.meals_cost || 0) + (day.activities_cost || 0))}
                    </div>
                    {expandedDays[day.day] ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </div>

                  {expandedDays[day.day] && (
                    <div className="day-details animate-slide-down">
                      {/* Transport */}
                      {day.transport && (
                        <div className="detail-section transport">
                          <div className="section-icon">🚗</div>
                          <div className="section-content">
                            <h4>Transport</h4>
                            <p>{day.transport}</p>
                            <span className="cost">{formatCurrency(day.transport_cost)}</span>
                          </div>
                        </div>
                      )}

                      {/* Hotel */}
                      {day.hotel && (
                        <div className="detail-section hotel">
                          <div className="section-icon">🏨</div>
                          <div className="section-content">
                            <h4>Accommodation</h4>
                            <p>{day.hotel}</p>
                            <span className="cost">{formatCurrency(day.hotel_cost)}</span>
                          </div>
                        </div>
                      )}

                      {/* Activities */}
                      {day.activities && day.activities.length > 0 && (
                        <div className="detail-section activities">
                          <div className="section-icon">🎯</div>
                          <div className="section-content">
                            <h4>Activities</h4>
                            <div className="activities-list">
                              {day.activities.map((activity, aIdx) => (
                                <div key={aIdx} className="activity-item">
                                  <span className="activity-time">{activity.time}</span>
                                  <div className="activity-info">
                                    <strong>{activity.activity}</strong>
                                    <span className="activity-location">{activity.location}</span>
                                    {activity.notes && <p className="activity-notes">{activity.notes}</p>}
                                  </div>
                                  {activity.cost_pkr > 0 && (
                                    <span className="activity-cost">{formatCurrency(activity.cost_pkr)}</span>
                                  )}
                                </div>
                              ))}
                            </div>
                          </div>
                        </div>
                      )}

                      {/* Meals */}
                      <div className="detail-section meals">
                        <div className="section-icon">🍽️</div>
                        <div className="section-content">
                          <h4>Meals</h4>
                          <p>Breakfast, Lunch, Dinner</p>
                          <span className="cost">{formatCurrency(day.meals_cost)}</span>
                        </div>
                      </div>

                      {/* Notes */}
                      {(day.weather_note || day.safety_note) && (
                        <div className="day-notes">
                          {day.weather_note && (
                            <div className="note weather-note">
                              <Cloud size={14} /> {day.weather_note}
                            </div>
                          )}
                          {day.safety_note && (
                            <div className="note safety-note">
                              <AlertTriangle size={14} /> {day.safety_note}
                            </div>
                          )}
                        </div>
                      )}

                      {/* Tips */}
                      {day.tips && day.tips.length > 0 && (
                        <div className="day-tips">
                          <h5>💡 Tips for this day:</h5>
                          <ul>
                            {day.tips.map((tip, tIdx) => (
                              <li key={tIdx}>{tip}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Cost Breakdown Tab */}
        {activeTab === 'costs' && (
          <div className="costs-content animate-fade-in">
            <div className="cost-summary-card">
              <h3>Total Trip Cost</h3>
              <div className="total-cost">
                {formatCurrency(tripPlan.cost_breakdown?.total)}
              </div>
              <p className="per-person">
                {formatCurrency(tripPlan.cost_breakdown?.per_person)} per person
              </p>
            </div>

            <div className="cost-breakdown-grid">
              <div className="cost-item">
                <div className="cost-icon transport">🚗</div>
                <div className="cost-details">
                  <span className="cost-label">Transport</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.transport)}</span>
                </div>
                <div className="cost-bar">
                  <div 
                    className="cost-fill transport" 
                    style={{ width: `${(tripPlan.cost_breakdown?.transport / tripPlan.cost_breakdown?.total) * 100}%` }}
                  />
                </div>
              </div>

              <div className="cost-item">
                <div className="cost-icon hotel">🏨</div>
                <div className="cost-details">
                  <span className="cost-label">Accommodation</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.accommodation)}</span>
                </div>
                <div className="cost-bar">
                  <div 
                    className="cost-fill hotel" 
                    style={{ width: `${(tripPlan.cost_breakdown?.accommodation / tripPlan.cost_breakdown?.total) * 100}%` }}
                  />
                </div>
              </div>

              <div className="cost-item">
                <div className="cost-icon food">🍽️</div>
                <div className="cost-details">
                  <span className="cost-label">Food & Meals</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.food)}</span>
                </div>
                <div className="cost-bar">
                  <div 
                    className="cost-fill food" 
                    style={{ width: `${(tripPlan.cost_breakdown?.food / tripPlan.cost_breakdown?.total) * 100}%` }}
                  />
                </div>
              </div>

              <div className="cost-item">
                <div className="cost-icon activities">🎯</div>
                <div className="cost-details">
                  <span className="cost-label">Activities</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.activities)}</span>
                </div>
                <div className="cost-bar">
                  <div 
                    className="cost-fill activities" 
                    style={{ width: `${(tripPlan.cost_breakdown?.activities / tripPlan.cost_breakdown?.total) * 100}%` }}
                  />
                </div>
              </div>

              <div className="cost-item">
                <div className="cost-icon misc">📦</div>
                <div className="cost-details">
                  <span className="cost-label">Miscellaneous</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.miscellaneous)}</span>
                </div>
                <div className="cost-bar">
                  <div 
                    className="cost-fill misc" 
                    style={{ width: `${(tripPlan.cost_breakdown?.miscellaneous / tripPlan.cost_breakdown?.total) * 100}%` }}
                  />
                </div>
              </div>

              <div className="cost-item buffer">
                <div className="cost-icon">🛡️</div>
                <div className="cost-details">
                  <span className="cost-label">Emergency Buffer (10%)</span>
                  <span className="cost-value">{formatCurrency(tripPlan.cost_breakdown?.buffer)}</span>
                </div>
              </div>
            </div>

            {tripPlan.cost_saving_tips && tripPlan.cost_saving_tips.length > 0 && (
              <div className="saving-tips">
                <h4>💰 Cost Saving Tips</h4>
                <ul>
                  {tripPlan.cost_saving_tips.map((tip, idx) => (
                    <li key={idx}>{tip}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Safety Tab */}
        {activeTab === 'safety' && (
          <div className="safety-content animate-fade-in">
            <div className="safety-grid">
              {/* Safety Notes */}
              {tripPlan.safety_notes && tripPlan.safety_notes.length > 0 && (
                <div className="safety-section">
                  <h4><AlertTriangle size={18} /> Safety Notes</h4>
                  <ul>
                    {tripPlan.safety_notes.map((note, idx) => (
                      <li key={idx}>{note}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Altitude Warnings */}
              {tripPlan.altitude_warnings && tripPlan.altitude_warnings.length > 0 && (
                <div className="safety-section altitude">
                  <h4><Mountain size={18} /> Altitude Warnings</h4>
                  <ul>
                    {tripPlan.altitude_warnings.map((warning, idx) => (
                      <li key={idx}>{warning}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Weather Warnings */}
              {tripPlan.weather_warnings && tripPlan.weather_warnings.length > 0 && (
                <div className="safety-section weather">
                  <h4><Cloud size={18} /> Weather Warnings</h4>
                  <ul>
                    {tripPlan.weather_warnings.map((warning, idx) => (
                      <li key={idx}>{warning}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Road Conditions */}
              {tripPlan.road_conditions && tripPlan.road_conditions.length > 0 && (
                <div className="safety-section roads">
                  <h4><MapPin size={18} /> Road Conditions</h4>
                  <ul>
                    {tripPlan.road_conditions.map((condition, idx) => (
                      <li key={idx}>{condition}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Connectivity */}
              {tripPlan.connectivity_notes && tripPlan.connectivity_notes.length > 0 && (
                <div className="safety-section connectivity">
                  <h4><Wifi size={18} /> Connectivity Notes</h4>
                  <ul>
                    {tripPlan.connectivity_notes.map((note, idx) => (
                      <li key={idx}>{note}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Fuel Stops */}
              {tripPlan.fuel_stops && tripPlan.fuel_stops.length > 0 && (
                <div className="safety-section fuel">
                  <h4><Fuel size={18} /> Fuel Stops</h4>
                  <ul>
                    {tripPlan.fuel_stops.map((stop, idx) => (
                      <li key={idx}>{stop}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Emergency Contacts */}
            {tripPlan.emergency_contacts && tripPlan.emergency_contacts.length > 0 && (
              <div className="emergency-contacts">
                <h4><Phone size={18} /> Emergency Contacts</h4>
                <div className="contacts-grid">
                  {tripPlan.emergency_contacts.map((contact, idx) => (
                    <div key={idx} className="contact-card">
                      <span className="contact-name">{contact.name}</span>
                      <a href={`tel:${contact.phone}`} className="contact-phone">{contact.phone}</a>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Documents Required */}
            {tripPlan.documents_required && tripPlan.documents_required.length > 0 && (
              <div className="documents-section">
                <h4>📄 Documents Required</h4>
                <ul>
                  {tripPlan.documents_required.map((doc, idx) => (
                    <li key={idx}><CheckCircle size={14} /> {doc}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Packing Tab */}
        {activeTab === 'packing' && (
          <div className="packing-content animate-fade-in">
            <div className="packing-intro">
              <h3>🎒 Packing Checklist for {tripPlan.destination}</h3>
              <p>Based on your {tripPlan.duration_days}-day {tripPlan.travel_style} trip</p>
            </div>

            <div className="packing-categories">
              {['documents', 'clothing', 'electronics', 'medicine', 'toiletries', 'misc'].map(category => {
                const items = tripPlan.packing_checklist?.filter(item => item.category === category) || []
                if (items.length === 0) return null
                
                return (
                  <div key={category} className="packing-category">
                    <h4>
                      {category === 'documents' && '📄 Documents'}
                      {category === 'clothing' && '👕 Clothing'}
                      {category === 'electronics' && '📱 Electronics'}
                      {category === 'medicine' && '💊 Medicine'}
                      {category === 'toiletries' && '🧴 Toiletries'}
                      {category === 'misc' && '📦 Miscellaneous'}
                    </h4>
                    <ul>
                      {items.map((item, idx) => (
                        <li key={idx} className={item.essential ? 'essential' : ''}>
                          <input type="checkbox" id={`item-${category}-${idx}`} />
                          <label htmlFor={`item-${category}-${idx}`}>
                            {item.item}
                            {item.essential && <span className="essential-badge">Essential</span>}
                            {item.notes && <span className="item-notes">{item.notes}</span>}
                          </label>
                        </li>
                      ))}
                    </ul>
                  </div>
                )
              })}
            </div>

            {/* Local Tips & Food */}
            <div className="extras-section">
              {tripPlan.local_tips && tripPlan.local_tips.length > 0 && (
                <div className="extras-card">
                  <h4>💡 Local Tips</h4>
                  <ul>
                    {tripPlan.local_tips.map((tip, idx) => (
                      <li key={idx}>{tip}</li>
                    ))}
                  </ul>
                </div>
              )}

              {tripPlan.food_recommendations && tripPlan.food_recommendations.length > 0 && (
                <div className="extras-card">
                  <h4><Utensils size={16} /> Food Recommendations</h4>
                  <ul>
                    {tripPlan.food_recommendations.map((food, idx) => (
                      <li key={idx}>{food}</li>
                    ))}
                  </ul>
                </div>
              )}

              {tripPlan.must_visit_spots && tripPlan.must_visit_spots.length > 0 && (
                <div className="extras-card">
                  <h4><Camera size={16} /> Must Visit Spots</h4>
                  <ul>
                    {tripPlan.must_visit_spots.map((spot, idx) => (
                      <li key={idx}>{spot}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Uncertainty Notes */}
      {tripPlan.uncertainty_notes && (
        <div className="uncertainty-banner">
          <AlertTriangle size={18} />
          <span>{tripPlan.uncertainty_notes}</span>
        </div>
      )}
    </div>
  )
}

export default ItineraryView
